# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
# install pylint with pip from requirements.txt
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
        - --max-line-length=80
        - --fail-under=0
        - --fail-on=F,E
        - --exit-zero
# install pytest with pip from requirements.txt
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest test
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
