apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: embedding-model-ingress
  namespace: semantic-search
spec:
  defaultBackend:
    service:
      name: embedding-model-service
      port:
        number: 8080
